spring.application.name=campusiq
spring.application.name=campusiq

# ===============================
# MySQL Database Configuration
# ===============================

spring.datasource.url=jdbc:postgresql://postgres:Bipul161%400406@db.zzlbsxnqdqokugsihwcl.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Bipul161@0604

# ===============================
# JPA / Hibernate Configuration
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# ==========================================
# CampusIQ Email Configuration
# ==========================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vipulpalthankyou@gmail.com
spring.mail.password=auqo cktk zgbx warr

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
